import MathlibNt.ChensTheorem
import MathlibNt.SieveTheory.LinearSieve

/-!
# Kernel trust audit

Run with `lake env lean Audit.lean` after `lake build`. The output must not
contain `sorryAx` for the conditional Chen-theorem derivations and the
imported PNT and Mertens interfaces.
-/

#print axioms MathlibNt.ChensTheorem.chens_theorem
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.key_inequality_implies_chen
#print axioms MathlibNt.SieveTheory.MertensTheorem.prime_number_theorem
#print axioms MathlibNt.SieveTheory.MertensTheorem.mertens_second_theorem
#print axioms MathlibNt.SieveTheory.MertensTheorem.mertens_product_formula
#print axioms MathlibNt.SieveTheory.MertensTheorem.primeProduct_asymptotic_order
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chen_pointwise_analytic_bounds_at
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chen_key_inequality_of_error_budget
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.range_sub_eq_one_card_le_one
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chenUnitCandidates_card_le_one
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chenWCandidate_mem_corrected_of_two_le
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chenWNonUnitCandidates_subset_correctedChenCandidates
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.chenWCandidates_card_le_correctedChenCandidates_card_add_one
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSiftingProduct_squarefree
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.prime_dvd_correctedChenSiftingProduct
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.coprime_correctedChenSiftingProduct_iff
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSiftedComplements_eq_correctedCandidate_image
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSiftedCard_eq_correctedCandidateCard
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenBoundingSieve_siftedSum_eq_card
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenTotalMass_eq
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenMultSum_eq_multiples_card
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenMultiples_card_eq_primeSupport
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenMultSum_eq_modEq_count
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenRem_eq_modEq_count
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenErrSum_eq_modEq
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenErrSum_le_panWeighted
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.ChenWeightedPanInput
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenPanSum_eq_weightedPanRemainder
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenDistributionCondition_iff_chenWeightedPanInput
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenErrSum_le_weightedPanInput
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenErrSum_uniform_of_weightedPanInput
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenErrSum_uniform_of_distribution
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenCandidates_card_ge_mainSum_sub_errSum
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenNu_inv_prime
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenNu_inv_prime_localFactor
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSelbergSum_eq_mertens_mul_localFactor_inv
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSelbergSum_mul_singularSeriesTruncated
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenSelbergSum_asymptotic_order
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.mem_correctedChenGood_or_bad
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenGoodCandidates_subset_goodRepresentations
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChenBad_penalty_ge_two
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_counting_bridge
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChen_cube_scale
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChen_floorZ_lt_y
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChen_cutoffValid_of_root_gt_two
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChen_cutoffValid_of_nine_le
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.correctedChen_candidate_complement_lt_cube
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_counting_bridge_public
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_counting_bridge_public_of_nine_le
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_key_inequality_implies_chen_at
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_key_inequality_implies_chen
#print axioms MathlibNt.SieveTheory.SwitchingPrinciple.corrected_chens_theorem
